name: Build and Test [Python 3.9, 3.10.4, 3.10.5]

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10.4, 3.10.5]

    steps:
      - uses: actions/checkout@v3
      - name: Build using Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install autopep8
          pip install --upgrade autopep8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: run linter [ autopep8]
        run: autopep8 .

      - name: run unit tests [pytest]
        run: pytest
# Runs a set of commands using the runners shell
          echo Add other actions to build,
          echo test, and deploy your project.
