name: Create Release Artifact

on:
  release:
    type: [published]

jobs:
  create-release-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build using Python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install autopep8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: run linter [autopep8]
        run: autopep8 .

      - name: run unit tests [pytest]
        run: pytest

      - name: create build artifact [sdist]
        run: python setup.py sdist

      - name: get release name
        id: get_release_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: limbus-${{ steps.get_release_name.outputs.VERSION }}
          path: dist/*
